# Generated by Django 5.2.7 on 2025-12-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
