# Generated by Django 5.2.7 on 2025-11-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_chatmessage_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
